language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t devonomy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devonomy/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  # DockerReact-env.eba-tqk2kc7t.us-east-2.elasticbeanstalk.com
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-201783581515"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY